name: Go

on:
  push:
    tags:
      -  "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build for Windows amd64
        run: go build -v -o d3servercheck.exe
        env:
          GOOS: "windows"
          GOARCH: "amd64"

      - name: Upload artifact Windows amd64
        uses: actions/upload-artifact@v1.0.0
        with:
          name:  d3servercheck
          path:  d3servercheck.exe
